# docker-compose down
# docker-compose up -d --build
# docker volume ls
# docker volume inspect <volume_name>
# docker volume prune

version: '3'

services:
  mongodb:
    image: mongo:4.2-bionic
    container_name: mongodb
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongodb:27017/

  python-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./applog:/usr/app/logs
    links:
     - mongodb